export declare const config: {
    printout: boolean;
};
export declare const message: {
    string: string;
    number: string;
    boolean: string;
    object: string;
    array: string;
    null: string;
    required: string;
    english: string;
    alphanum: string;
    nospace: string;
    nodbc: string;
    qq: string;
    age: string;
    zipcode: string;
    ip: string;
    port: string;
    domain: string;
    bizcode: string;
    invoice: string;
    bankcard: string;
    currency: string;
    float: string;
    int: string;
    decimal: string;
    chinese: string;
    mail: string;
    url: string;
    account: string;
    password: string;
    safe: string;
    hex: string;
    color: string;
    ascii: string;
    base64: string;
    md5: string;
    uuid: string;
    mobile: string;
    telphone: string;
    phone: string;
    percent: string;
    year: string;
    month: string;
    day: string;
    hour: string;
    minute: string;
    time: string;
    date: string;
    datetime: string;
    file: string;
    image: string;
    word: string;
    lon: string;
    lat: string;
    approval: string;
    citycode: string;
    address: string;
    upper: string;
    lower: string;
    isbn: string;
    tag: string;
    jwt: string;
    maca: string;
    even: string;
    odd: string;
    ipv6: string;
    bodycard: string;
    autocard: string;
    not: string;
    eq: string;
    gt: string;
    gte: string;
    lt: string;
    lte: string;
    between: string;
    min: string;
    max: string;
    len: string;
    minlen: string;
    maxlen: string;
    charlen: string;
    in: string;
    has: string;
    empty: string;
    regexp: string;
    custom: string;
    customItems: {};
};
interface CustomType {
    customItems?: {
        [key: string]: string;
    };
    [key: string]: string | {
        [key: string]: string;
    };
}
export declare type MessageInfo = Partial<Record<Exclude<keyof typeof message, 'customItems'>, string>> & CustomType;
export {};
