export interface MessageInfo {
  string?: string;
  number?: string;
  boolean?: string;
  object?: string;
  array?: string;
  null?: string;
  required?: string;
  english?: string;
  alphanum?: string;
  nospace?: string;
  nodbc?: string;
  qq?: string;
  age?: string;
  zipcode?: string;
  ip?: string;
  port?: string;
  domain?: string;
  bizcode?: string;
  invoice?: string;
  bankcard?: string;
  currency?: string;
  float?: string;
  int?: string;
  decimal?: string;
  chinese?: string;
  mail?: string;
  url?: string;
  account?: string;
  password?: string;
  safe?: string;
  hex?: string;
  color?: string;
  ascii?: string;
  base64?: string;
  md5?: string;
  uuid?: string;
  mobile?: string;
  telphone?: string;
  phone?: string;
  percent?: string;
  year?: string;
  month?: string;
  day?: string;
  hour?: string;
  minute?: string;
  time?: string;
  date?: string;
  datetime?: string;
  file?: string;
  image?: string;
  word?: string;
  lon?: string;
  lat?: string;
  approval?: string;
  citycode?: string;
  address?: string;
  upper?: string;
  lower?: string;
  isbn?: string;
  tag?: string;
  jwt?: string;
  maca?: string;
  even?: string;
  odd?: string;
  ipv6?: string;
  bodycard?: string;
  autocard?: string;
  not?: string;
  eq?: string;
  gt?: string;
  gte?: string;
  lt?: string;
  lte?: string;
  between?: string;
  min?: string;
  max?: string;
  length?: string;
  minlength?: string;
  maxlength?: string;
  bitmax?: string;
  in?: string;
  has?: string;
  empty?: string;
  regexp?: string;
  custom?: string;
  customItems?: {
    [key: string]: string;
  };
  [key: string]:
    | string
    | {
        [key: string]: string;
      };
}

export var config = {
  printout: false 
}

export var message: MessageInfo = {
  string: '%n必须是字符串类型！',
  number: '%n必须是数字类型！',
  boolean: '%n必须是布尔类型！',
  object: '%n必须是对象类型！',
  array: '%n必须是数组类型！',
  null: '%n必须是Null类型！',
  required: '%n要求必填！',
  english: '%n必须是英文！',
  alphanum: '%n必须是字母与数字混合！',
  nospace: '%n不含空格的内容！',
  nodbc: '%n不含全角字符的内容！',
  qq: '%n必须是QQ号码格式！',
  age: '%n必须是0~129的年龄数字！',
  zipcode: '%n必须是合法邮编格式！',
  ip: '%n必须是合法IPV4地址格式！',
  port: '%n必须是合法端口！',
  domain: '%n必须是域名格式！',
  bizcode: '%n必须是统一信用编码格式！',
  invoice: '%n必须是增值税号格式！',
  bankcard: '%n必须是银行卡号格式！',
  currency: '%n必须是货币格式！',
  float: '%n必须是浮点数！',
  int: '%n必须是整数！',
  decimal: '%n必须是小数！',
  chinese: '%n必须是中文！',
  mail: '%n必须是邮箱格式！',
  url: '%n必须是网址格式！',
  account: '%n必须是字母与_数字的组合，且首位为字母！',
  password: '%n最少包含1个大小写字母、特殊字符、数字！',
  safe: '%n不含SQL敏感关键字符的内容！',
  hex: '%n必须是HAX格式！',
  color: '%n必须是颜色格式！',
  ascii: '%n必须是ASCII格式！',
  base64: '%n必须是BASE64格式！',
  md5: '%n必须是MD5格式！',
  uuid: '%n必须是HAX格式！',
  mobile: '%n手机号码格式不对！',
  telphone: '%n电话号码格式不对！',
  phone: '%n手机或电话号码格式不对！',
  percent: '%n必须是百分数！',
  year: '%n必须是四位年份数字！',
  month: '%n必须是1~12月份数字！',
  day: '%n必须是1~31日的数字！',
  hour: '%n必须是0~23小时数字！',
  minute: '%n必须是0~59分秒数字！',
  time: '%n时分秒的时间格式不对！',
  date: '%n日期格式不对！',
  datetime: '%n日期与时间格式不对！',
  file: '%n必须是合法文件名！',
  image: '%n必须是合法图片文件名！',
  word: '%n必须是合法文档文件名！',
  lon: '%n必须符合经度格式，带1位以上小数点！',
  lat: '%n必须符合纬度格式，带1位以上小数点！',
  approval: '%n必须是审批文号格式！',
  citycode: '%n必须是6位地区代码！',
  address: '%n必须是带镇与街道的地址！',
  upper: '%n必须要有大写！',
  lower: '%n必须要有小写！',
  isbn: '%n必须是13位书号格式！',
  tag: '%n必须是闭合标签格式！',
  jwt: '%n必须是JWT字符串格式！',
  maca: '%n必须是MAC地址格式！',
  even: '%n必须是偶数！',
  odd: '%n必须是奇数！',
  ipv6: '%n必须是IPV6地址格式！',
  bodycard: '%n必须是合法身份证号格式！',
  autocard: '%n必须是合法车牌号格式！',
  not: '%n不能等于%t！',
  eq: '%n必须等于%t！',
  gt: '%n要大于%t！',
  gte: '%n要大于等于%t！',
  lt: '%n要小于%t！',
  lte: '%n要小于等于%t！',
  between: '%n要大于%t，小于%t！',
  min: '%n必须是在%t内最小的值！',
  max: '%n必须是在%t内最大的值！',
  length: '%n长度要等于%t！',
  minlength: '%n最小长度应为%t ！',
  maxlength: '%n最大长度应为%t！',
  bitmax: '%n最大字节长度应为%t！',
  in: '%n不在%t之内！',
  has: '%n不在%t包含范围！',
  empty: '%n必须是空的值！',
  regexp: '%n没有匹配正确！',
  custom: '%n未通过验证！',
  customItems: {}
};
