export const config = {
    printout: false,
};

export const message = {
    string: '%n必须是字符串类型！',
    number: '%n必须是数字类型！',
    boolean: '%n必须是布尔类型！',
    object: '%n必须是对象类型！',
    array: '%n必须是数组类型！',
    null: '%n必须是Null值！',
    required: '%n不能为空！',
    english: '%n必须是英文字母！',
    alphanum: '%n必须是字母与数字混合！',
    nospace: '%n不得含任何空格字符！',
    nodbc: '%n不得含任何全角字符！',
    qq: '%n必须是首位不为0的5~11位的数字！',
    age: '%n必须是0~129的年龄数字！',
    zipcode: '%n邮编格式不对！',
    ip: '%nIPV4地址格式不对！',
    port: '%n端口格式不对！',
    domain: '%n域名格式不对！',
    bizcode: '%n统一信用编码格式不对！',
    invoice: '%n增值税号格式有误！',
    bankcard: '%n银行卡号格式有误！',
    currency: '%n货币格式有误！',
    float: '%n必须是浮点数！',
    int: '%n必须是整数！',
    decimal: '%n必须是小数！',
    chinese: '%n必须是中文！',
    mail: '%n邮箱格式不对！',
    url: '%n网址格式有误！',
    account: '%n必须是字母与_数字的组合，且首位为字母！',
    password: '%n最少包含1个大小写字母、特殊字符、数字！',
    safe: '%n不得含SQL敏感字符！',
    hex: '%nHAX格式有误！',
    color: '%n颜色值格式有误！',
    ascii: '%nASCII格式有误！',
    base64: '%nBASE64格式有误！',
    md5: '%nMD5格式有误！',
    uuid: '%nUUID或GUID格式有误！',
    mobile: '%n手机号码格式不对！',
    telphone: '%n电话号码格式不对！',
    phone: '%n手机或电话号码格式不对！',
    percent: '%n必须是百分数！',
    year: '%n必须是四位年份数字！',
    month: '%n必须是1~12月份数字！',
    day: '%n必须是1~31日的数字！',
    hour: '%n必须是0~23小时数字！',
    minute: '%n必须是0~59分秒数字！',
    time: '%n时分秒的时间格式不对！',
    date: '%n日期格式不对！',
    datetime: '%n日期与时间格式不对！',
    file: '%n必须是合法文件名！',
    image: '%n必须是合法图片文件名！',
    word: '%n必须是合法文档文件名！',
    lon: '%n必须符合经度格式，带1位以上小数点！',
    lat: '%n必须符合纬度格式，带1位以上小数点！',
    approval: '%n必须是审批文号格式！',
    citycode: '%n必须是6位地区代码！',
    address: '%n必须是带镇与街道的地址！',
    upper: '%n必须要有大写！',
    lower: '%n必须要有小写！',
    isbn: '%n必须是13位书号格式！',
    tag: '%n必须是闭合标签格式！',
    jwt: '%n必须是JWT字符串格式！',
    maca: '%n必须是MAC地址格式！',
    even: '%n必须是偶数！',
    odd: '%n必须是奇数！',
    ipv6: '%n必须是IPV6地址格式！',
    bodycard: '%n必须是合法身份证号格式！',
    autocard: '%n必须是合法车牌号格式！',
    not: '%n不能等于%t！',
    eq: '%n必须等于%t！',
    gt: '%n要大于%t！',
    gte: '%n要大于等于%t！',
    lt: '%n要小于%t！',
    lte: '%n要小于等于%t！',
    between: '%n要大于%t，小于%t！',
    min: '%n必须是在%t内最小的值！',
    max: '%n必须是在%t内最大的值！',
    len: '%n长度要等于%t！',
    minlen: '%n最小长度应为%t ！',
    maxlen: '%n最大长度应为%t！',
    charlen: '%n最大字节长度应为%t！',
    in: '%n不在%t之内！',
    has: '%n不在%t包含范围！',
    empty: '%n必须是空的值！',
    regexp: '%n没有匹配正确！',
    custom: '%n未通过验证！',
    customItems: {},
};

interface CustomType {
    customItems?: {
        [key: string]: string;
    };
    [key: string]: | string | {
        [key: string]: string;
    };
}
export type MessageInfo = Partial<Record<Exclude<keyof typeof message,
'customItems'>, string>> & CustomType;
